name = "movie-diary"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "movie-diary-db"
database_id = "b1157762-e450-4dab-ab34-1d7ad9d1e740"
migrations_dir = "database/migrations"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "movie-diary-photos"

# Local dev overrides (used by `wrangler pages dev`)
[dev]
port = 3000
local_protocol = "http"
